### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by kabutz** [aalmiray/java-champions#229]
These produce 404's: 

https://javachampions.org/css/fontawesome-all.min.css - Linked from: https://javachampions.org/ and 4 more

https://javachampions.org/js/4-shims.js - Linked from: https://javachampions.org/ and 4 more

https://sessionize.com/james-ward - Linked from: https://javachampions.org/members.html 
    Probably should be https://sessionize.com/jamesward

https://mastodon.social/@yanaga - Linked from: https://javachampions.org/members.html
    Probably should be https://mastodon.online/@yanaga

**Comment by kabutz** [comment]
Oh and this causes a timeout:

https://juddsolutions.com/ - Linked from: https://javachampions.org/members.html
Probably should be Linked from: https://www.juddsolutions.com/

**Comment by aalmiray** [comment]
I believe I fixed all issues. Thanks @kabutz 😅
