### ISSUE TITLE
Can Oracle employees be Java Champions now, too?

### ISSUE THREAD

**Issue by keilw** [aalmiray/java-champions#34]
@aalmiray you recently joined Oracle, congratulations btw, but, doesn't that mean you have to "pause" your Java Champion status while you work there or has that changed lately?
Guess for @steveonjava it's correct again as he left Oracle ;-)

**Comment by kabutz** [comment]
This repository does not differentiate between normal JCs and those who are "paused" because they joined Oracle. In my view, all are the same anyway ;-)

**Comment by keilw** [comment]
Except those who passed ;-) But since there is no separation between "emeritus" and active here, I guess it's ok.
