### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by bmarwell** [aalmiray/java-champions#65]
Images are dead links.

**Comment by aalmiray** [comment]
Yeah. We've switched avatar providers twice already. There's  a need for a reliable service that can take a twitter username as input and return a suitable avatar image.

**Comment by myfear** [comment]
What about https://en.gravatar.com/

**Comment by aalmiray** [comment]
gravatar requires an email address. I'd rather not disclose that personal information unless each JC agrees to.

**Comment by bmarwell** [comment]
Uh, we could write a simple java tool which fetches the images and uploads them to this repo, I guess? :D

**Comment by aalmiray** [comment]
Done using a https://github.com/jbangdev/jbang powered script.
Updates triggered manually via a GitHub Action.
Will setup a cron job later.
